##
## EPITECH PROJECT, 2020
## CPE_corewar_2019
## File description:
## Makefile
##

all:
	@make -sC corewar-cli
	@cp corewar-cli/corewar ./

clean:
	@make clean -sC corewar-cli
	@make clean -sC libcorewar

fclean:
	@make fclean -sC corewar-cli
	@make fclean -sC libcorewar
	@rm -f corewar

re:
	@make re -sC corewar-cli
