name: Continuous Integration

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

env:
  CC: gcc-9

jobs:
  build_asm:

    name: Build compiler
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build compiler
        working-directory: ./asm
        run: make

  build_vm:

    name: Build VM
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build VM
        working-directory: ./corewar
        run: make

  install_criterion:
    
    name: Install criterion
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/cache@v1
        id: cache
        env:
          cache-name: cache-criterion
        with:
          path: ${{ runner.temp }}/Criterion
          key: ${{ runner.os }}-${{ env.cache-name }}

      - name: Clone Criterion
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ runner.temp }}
        run: git clone --recursive https://github.com/Snaipe/Criterion.git --branch=master --depth=1

      - name: Build Criterion
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ${{ runner.temp }}/Criterion
        run: mkdir build && cd build && cmake .. && cmake --build .

  test_asm:

    name: Test compiler
    needs: [build_asm, install_criterion]
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        working-directory: ./asm
        run: make tests_run
        env:
          LD_LIBRARY_PATH: ${{ runner.temp }}/Criterion/build:${{ env.LD_LIBRARY_PATH }}
          LIBRARY_PATH: ${{ runner.temp }}/Criterion/build:${{ env.LIBRARY_PATH }}
          CPATH: ${{ runner.temp }}/Criterion/include:${{ env.CPATH }}

  test_vm:

    name: Test VM
    needs: [build_asm, install_criterion]
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        working-directory: ./corewar
        run: make tests_run
        env:
          LD_LIBRARY_PATH: ${{ runner.temp }}/Criterion/build:${{ env.LD_LIBRARY_PATH }}
          LIBRARY_PATH: ${{ runner.temp }}/Criterion/build:${{ env.LIBRARY_PATH }}
          CPATH: ${{ runner.temp }}/Criterion/include:${{ env.CPATH }}
