name: Continuous Integration

on: [push, pull_request]

jobs:
  build_asm:

    name: Build compiler
    runs-on: [ubuntu-latest]
    container:
      image: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2

      - name: Build compiler
        working-directory: ./asm
        run: make

  build_vm:

    name: Build VM
    runs-on: [ubuntu-latest]
    container:
      image: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2

      - name: Build VM
        working-directory: ./corewar
        run: make

  test_asm:

    name: Test compiler
    needs: [build_asm]
    runs-on: [ubuntu-latest]
    container:
      image: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        working-directory: ./asm
        run: make tests_run

  test_vm:

    name: Test VM
    needs: [build_asm]
    runs-on: [ubuntu-latest]
    container:
      image: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        working-directory: ./corewar
        run: make tests_run
