name: Continuous Integration

on: [push, pull_request]

jobs:
  asm:

    name: Build compiler
    runs-on: [ubuntu-latest]
    container:
      image: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ./asm
        run: make

      - name: Test
        working-directory: ./asm
        run: make tests_run

  vm:

    name: Build VM
    runs-on: [ubuntu-latest]
    container:
      image: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: ./corewar
        run: make

      - name: Test
        working-directory: ./corewar
        run: make tests_run
